[module]
  [module.hugoVersion]
    min = "0.113.0"

[[menu.main]]
identifier = "post"
name = "Posts"
url = "/"
weight = 1
[[menu.main]]
identifier = "archives"
name = "Archive"
url = "/post/"
weight = 2
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[taxonomies]
tags = "tags"

[params]
title="TeXify2"
description = "TeXify2 - a minimal, latex-style hugo theme for personal blogging"
images = ['images/logo.jpg']
footnote = """
Follow me on <a class=link href=https://github.com/weastur target=_blank rel=noopener>GitHub</a>,
<a class=link href=https://www.linkedin.com/in/weastur/ target=_blank rel=noopener>LinkedIn</a> or
<a class=link href=/index.xml>RSS</a> |
<a class=link href=https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en target=_blank rel=noopener>CC BY-NC-SA 4.0</a>
"""
keywords = ["hugo", "latex", "theme", "blog", "texify", "texify2", "weastur"]
customCSS = []
customJS = []
dateFormat = "January 2, 2006"
emphasisWithDots = true
since = "2023"
toc = false
showWordCount = true
showReadingTime = true
rootFontSize = "120%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = false

[params.commentEngine]
code = """
"""

[params.buymeacoffee]
code = """
"""

[params.sharingbuttons]
facebook = true
twitter = true
email = true
linkedin = true
reddit = true
whatsapp = true
hackernews = true
telegram = true
